[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "flask-sqlalchemy==3.1.1",
    "flask==3.0.0",
    "python-dotenv>=1.1.1",
    "requests>=2.32.5",
    "flask-cors==4.0.0",
    "selenium>=4.37.0",
]
